theme: jekyll-theme-slate
title: Hi, I'm Cam Rodriguez.
description: This is going to serve as an extension of my personal portfolio, and consolidate all of my projects and information in one place! Like LinkedIn, except I made it myself.
